services:

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: testdb
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    image: 108782069184.dkr.ecr.us-east-1.amazonaws.com/backend:latest
    environment:
      DB_HOST: postgres
      DB_USER: testuser
      DB_PASSWORD: testpass
      DB_NAME: testdb
    depends_on:
      - postgres

  frontend:
    image: 108782069184.dkr.ecr.us-east-1.amazonaws.com/frontend:latest
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend

volumes:
  pgdata:
